#!/usr/bin/env python3
"""Regenerate arm64-linux/sources and arm64-linux/lists from upstream.

    python3 tools/make-arm64-linux.py [--work DIR]

Everything in arm64-linux/ except target.json and README.md is produced by
this script, from two upstream releases:

    musl 1.2.5          https://musl.libc.org/releases/musl-1.2.5.tar.gz
    LLVM 22.1.4         https://github.com/llvm/llvm-project  (tag llvmorg-22.1.4)
                        libc++, libc++abi, libunwind, compiler-rt builtins

To move to a newer release, change the versions below, run this, and rebuild a
program with --target arm64-linux: the runtime is keyed by the package version,
so bump "version" in target.json too, or installed copies will keep using the
runtime they already compiled.

Nothing here compiles anything. It downloads, selects, and copies source files,
and writes the handful of headers that musl's and libc++'s own build systems
would otherwise have generated. Needs git (for a sparse checkout of LLVM, which
downloads only the directories used) and network access.
"""

import argparse
import glob
import os
import re
import shutil
import subprocess
import tarfile
import urllib.request

MUSL_VERSION = '1.2.5'
MUSL_URL = 'https://musl.libc.org/releases/musl-%s.tar.gz' % MUSL_VERSION
LLVM_TAG = 'llvmorg-22.1.4'
LLVM_URL = 'https://github.com/llvm/llvm-project.git'
ARCH = 'aarch64'

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, '..', 'arm64-linux'))
SRC = os.path.join(OUT, 'sources')
LISTS = os.path.join(OUT, 'lists')

# The parts of libc++, libc++abi and libunwind that are compiled rather than
# header-only -- and only the parts a Nexa program on this target reaches.
# Found by linking every std module's programs and adding what the linker
# asked for, so a file here is here because something needed it.
LIBCXX_SRC = [
    'new.cpp', 'new_helpers.cpp', 'verbose_abort.cpp', 'string.cpp',
    'random.cpp', 'thread.cpp', 'system_error.cpp', 'mutex.cpp',
    'condition_variable.cpp', 'future.cpp', 'stdexcept.cpp', 'exception.cpp',
    'typeinfo.cpp', 'error_category.cpp',
]
LIBCXXABI_SRC = [
    'cxa_guard.cpp', 'abort_message.cpp', 'cxa_handlers.cpp', 'cxa_default_handlers.cpp',
    'cxa_aux_runtime.cpp', 'cxa_exception.cpp', 'cxa_exception_storage.cpp', 'cxa_personality.cpp',
    'cxa_vector.cpp', 'cxa_virtual.cpp', 'fallback_malloc.cpp', 'private_typeinfo.cpp',
    'stdlib_exception.cpp', 'stdlib_stdexcept.cpp', 'stdlib_typeinfo.cpp', 'cxa_demangle.cpp',
    'cxa_thread_atexit.cpp',
]
# EHABI is 32-bit ARM's, SEH is Windows', sjlj/wasm/AIX are other platforms'.
LIBUNWIND_SRC = [
    'libunwind.cpp', 'UnwindLevel1.c', 'UnwindLevel1-gcc-ext.c',
    'UnwindRegistersRestore.S', 'UnwindRegistersSave.S',
]

# libc++'s site configuration. CMake writes this from __config_site.in; here
# every answer is fixed by the target, so it is written out once.
CONFIG_SITE = """\
// libc++'s site configuration for Nexa's arm64-linux target: AArch64 Linux,
// musl, statically linked. Normally generated by CMake from __config_site.in;
// written out here because this target is built from source by NexaC, not by
// CMake, and every value is fixed by the target anyway.
#ifndef _LIBCPP___CONFIG_SITE
#define _LIBCPP___CONFIG_SITE

#define _LIBCPP_ABI_VERSION 1
#define _LIBCPP_ABI_NAMESPACE __1
#define _LIBCPP_ABI_FORCE_ITANIUM 0
#define _LIBCPP_ABI_FORCE_MICROSOFT 0
#define _LIBCPP_HAS_THREADS 1
#define _LIBCPP_HAS_MONOTONIC_CLOCK 1
#define _LIBCPP_HAS_TERMINAL 1
#define _LIBCPP_HAS_MUSL_LIBC 1
#define _LIBCPP_HAS_THREAD_API_PTHREAD 1
#define _LIBCPP_HAS_THREAD_API_EXTERNAL 0
#define _LIBCPP_HAS_THREAD_API_WIN32 0
#define _LIBCPP_HAS_THREAD_API_C11 0
#define _LIBCPP_HAS_VENDOR_AVAILABILITY_ANNOTATIONS 0
#define _LIBCPP_HAS_FILESYSTEM 1
#define _LIBCPP_HAS_RANDOM_DEVICE 1
#define _LIBCPP_HAS_LOCALIZATION 1
#define _LIBCPP_HAS_UNICODE 1
#define _LIBCPP_HAS_WIDE_CHARACTERS 1
#define _LIBCPP_HAS_TIME_ZONE_DATABASE 0
#define _LIBCPP_INSTRUMENTED_WITH_ASAN 0

#define _LIBCPP_PSTL_BACKEND_SERIAL

#define _LIBCPP_HARDENING_MODE_DEFAULT _LIBCPP_HARDENING_MODE_NONE
#define _LIBCPP_ASSERTION_SEMANTIC_DEFAULT _LIBCPP_ASSERTION_SEMANTIC_HARDENING_DEPENDENT

#define _LIBCPP_LIBC_PICOLIBC 0
#define _LIBCPP_LIBC_NEWLIB 0

#endif // _LIBCPP___CONFIG_SITE
"""


def copy(src, dst):
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copy2(src, dst)


def copytree(src, dst):
    shutil.copytree(src, dst, dirs_exist_ok=True)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', newline='\n') as f:
        f.write(text)


def write_list(name, header, files):
    write(os.path.join(LISTS, name), ''.join('# ' + h + '\n' for h in header) + ''.join(f + '\n' for f in files))


def fetch(work):
    os.makedirs(work, exist_ok=True)
    musl = os.path.join(work, 'musl-' + MUSL_VERSION)
    if not os.path.isdir(musl):
        tgz = musl + '.tar.gz'
        print('downloading', MUSL_URL)
        urllib.request.urlretrieve(MUSL_URL, tgz)
        with tarfile.open(tgz) as t:
            t.extractall(work)
    llvm = os.path.join(work, 'llvm-project')
    if not os.path.isdir(llvm):
        print('sparse-cloning', LLVM_URL, LLVM_TAG)
        subprocess.check_call(['git', 'clone', '--quiet', '--depth', '1', '--branch', LLVM_TAG,
                               '--filter=blob:none', '--sparse', LLVM_URL, llvm])
        subprocess.check_call(['git', '-C', llvm, 'sparse-checkout', 'set',
                               'libcxx/include', 'libcxx/src', 'libcxx/vendor',
                               'libcxxabi/include', 'libcxxabi/src',
                               'libunwind/include', 'libunwind/src',
                               'compiler-rt/lib/builtins'])
    return musl, llvm


# --- musl ----------------------------------------------------------------------
#
# musl's Makefile builds every src/*/*.c (plus src/malloc/mallocng and crt/),
# except that a file of the same stem in the architecture's subdirectory --
# src/string/aarch64/memcpy.S for src/string/memcpy.c -- replaces it.

def musl_sources(musl):
    rel = lambda p: os.path.relpath(p, musl).replace('\\', '/')
    dirs = sorted(d for d in glob.glob(os.path.join(musl, 'src', '*')) if os.path.isdir(d))
    dirs += [os.path.join(musl, 'src', 'malloc', 'mallocng'), os.path.join(musl, 'crt')]
    out = []
    for d in dirs:
        arch_dir = os.path.join(d, ARCH)
        arch = sorted(glob.glob(os.path.join(arch_dir, '*.[csS]')))
        replaced = {os.path.splitext(os.path.basename(a))[0] for a in arch}
        for c in sorted(glob.glob(os.path.join(d, '*.c'))):
            if os.path.splitext(os.path.basename(c))[0] not in replaced:
                out.append(rel(c))
        out += [rel(a) for a in arch]
    return out


def mkalltypes(lines):
    """tools/mkalltypes.sed, in Python."""
    out = []
    for line in lines:
        m = re.match(r'^TYPEDEF (.*) ([^ ]*);$', line)
        if m:
            t, n = m.group(1), m.group(2)
            out.append('#if defined(__NEED_%s) && !defined(__DEFINED_%s)\ntypedef %s %s;\n#define __DEFINED_%s\n#endif\n'
                       % (n, n, t, n, n))
            continue
        m = re.match(r'^STRUCT * ([^ ]*) (.*);$', line)
        if m:
            n, b = m.group(1), m.group(2)
            out.append('#if defined(__NEED_struct_%s) && !defined(__DEFINED_struct_%s)\nstruct %s %s;\n#define __DEFINED_struct_%s\n#endif\n'
                       % (n, n, n, b, n))
            continue
        m = re.match(r'^UNION * ([^ ]*) (.*);$', line)
        if m:
            n, b = m.group(1), m.group(2)
            out.append('#if defined(__NEED_union_%s) && !defined(__DEFINED_union_%s)\nunion %s %s;\n#define __DEFINED_union_%s\n#endif\n'
                       % (n, n, n, b, n))
            continue
        out.append(line)
    return ''.join(l + '\n' for l in out)


def build_musl(musl):
    files = musl_sources(musl)
    m_out = os.path.join(SRC, 'musl')
    for f in files:
        copy(os.path.join(musl, f), os.path.join(m_out, f))
    # Every header under src/ -- sources include their neighbours -- except
    # those in another architecture's override directory.
    arches = set(os.listdir(os.path.join(musl, 'arch')))
    for h in glob.glob(os.path.join(musl, 'src', '**', '*.h'), recursive=True):
        parts = os.path.relpath(h, musl).replace('\\', '/').split('/')
        if len(parts) >= 4 and parts[2] in arches and parts[2] != ARCH:
            continue
        copy(h, os.path.join(m_out, *parts))
    copytree(os.path.join(musl, 'include'), os.path.join(m_out, 'include'))
    copytree(os.path.join(musl, 'arch', ARCH), os.path.join(m_out, 'arch', ARCH))
    copytree(os.path.join(musl, 'arch', 'generic'), os.path.join(m_out, 'arch', 'generic'))
    for f in ('COPYRIGHT', 'VERSION', 'README'):
        copy(os.path.join(musl, f), os.path.join(m_out, f))

    # The three headers musl's Makefile generates.
    gen = os.path.join(SRC, 'musl-gen')
    read = lambda p: open(os.path.join(musl, p), newline='').read().splitlines()
    write(os.path.join(gen, 'include', 'bits', 'alltypes.h'),
          mkalltypes(read('arch/%s/bits/alltypes.h.in' % ARCH) + read('include/alltypes.h.in')))
    sc = read('arch/%s/bits/syscall.h.in' % ARCH)
    write(os.path.join(gen, 'include', 'bits', 'syscall.h'),
          ''.join(l + '\n' for l in sc) + ''.join(l.replace('__NR_', 'SYS_', 1) + '\n' for l in sc if '__NR_' in l))
    write(os.path.join(gen, 'src', 'internal', 'version.h'), '#define VERSION "%s"\n' % MUSL_VERSION)

    write_list('musl.txt', [
        'musl %s, the files its Makefile builds for %s: every src/*/*.c,' % (MUSL_VERSION, ARCH),
        'except where src/*/%s/ has a file of the same name, which replaces it.' % ARCH,
        'Relative to sources/musl. The crt/ start files are in target.json instead.',
    ], [f for f in files if not f.startswith('crt/')])
    return files


# --- compiler-rt builtins --------------------------------------------------------

def cmake_list(text, name):
    m = re.search(r'^set\(' + name + r'\s*\n(.*?)^\)', text, re.S | re.M)
    return [l.strip() for l in m.group(1).splitlines()
            if l.strip() and not l.strip().startswith('#') and '${' not in l]


def build_builtins(llvm):
    B = os.path.join(llvm, 'compiler-rt', 'lib', 'builtins')
    cm = open(os.path.join(B, 'CMakeLists.txt'), encoding='utf-8').read()
    # aarch64_SOURCES in the same file: the two generic lists plus two of its
    # own. The SME and outline-atomics extras are left out: the target builds
    # with -mno-outline-atomics, and nothing here uses SME.
    files = cmake_list(cm, 'GENERIC_TF_SOURCES') + cmake_list(cm, 'GENERIC_SOURCES') + \
        ['cpu_model/%s.c' % ARCH, '%s/fp_mode.c' % ARCH]
    files = [f for f in files if f != 'enable_execute_stack.c']
    b_out = os.path.join(SRC, 'compiler-rt', 'lib', 'builtins')
    for f in os.listdir(B):
        p = os.path.join(B, f)
        if os.path.isfile(p) and f.endswith(('.c', '.h', '.inc', '.def')):
            copy(p, os.path.join(b_out, f))
    copytree(os.path.join(B, ARCH), os.path.join(b_out, ARCH))
    copytree(os.path.join(B, 'cpu_model'), os.path.join(b_out, 'cpu_model'))
    copy(os.path.join(llvm, 'compiler-rt', 'LICENSE.TXT'), os.path.join(SRC, 'compiler-rt', 'LICENSE.TXT'))
    write_list('builtins.txt', [
        "compiler-rt's builtins for %s, as its CMakeLists.txt lists them:" % ARCH,
        'GENERIC_TF_SOURCES + GENERIC_SOURCES + the two %s files. The SME' % ARCH,
        'and outline-atomics extras are left out (the target builds with',
        '-mno-outline-atomics). Relative to sources/compiler-rt/lib/builtins.',
    ], files)
    return files


# --- libc++, libc++abi, libunwind --------------------------------------------------

def build_cxx(llvm):
    L = os.path.join(llvm, 'libcxx')
    x_out = os.path.join(SRC, 'libcxx')
    copytree(os.path.join(L, 'include'), os.path.join(x_out, 'include'))
    copytree(os.path.join(L, 'src', 'include'), os.path.join(x_out, 'src', 'include'))
    copytree(os.path.join(L, 'src', 'support'), os.path.join(x_out, 'src', 'support'))
    for f in LIBCXX_SRC:
        copy(os.path.join(L, 'src', f), os.path.join(x_out, 'src', f))
    copy(os.path.join(L, 'LICENSE.TXT'), os.path.join(x_out, 'LICENSE.TXT'))
    write(os.path.join(SRC, 'libcxx-gen', '__config_site'), CONFIG_SITE)
    copy(os.path.join(L, 'vendor', 'llvm', 'default_assertion_handler.in'),
         os.path.join(SRC, 'libcxx-gen', '__assertion_handler'))
    write_list('libcxx.txt', [
        'The parts of libc++ that are compiled rather than header-only, and only',
        'the ones a Nexa program on this target reaches. Relative to sources/libcxx.',
    ], ['src/' + f for f in LIBCXX_SRC])

    A = os.path.join(llvm, 'libcxxabi')
    a_out = os.path.join(SRC, 'libcxxabi')
    copytree(os.path.join(A, 'include'), os.path.join(a_out, 'include'))
    for f in os.listdir(os.path.join(A, 'src')):
        if f.endswith(('.h', '.inc')) or f in LIBCXXABI_SRC:
            copy(os.path.join(A, 'src', f), os.path.join(a_out, 'src', f))
    copytree(os.path.join(A, 'src', 'demangle'), os.path.join(a_out, 'src', 'demangle'))
    copy(os.path.join(A, 'LICENSE.TXT'), os.path.join(a_out, 'LICENSE.TXT'))
    write_list('libcxxabi.txt', [
        'The parts of libc++abi a Nexa program on this target reaches: exceptions',
        '(throwing, catching, the personality routine and the type information a',
        'catch matches against), the static-initialisation guard, terminate and',
        'its handlers. Relative to sources/libcxxabi.',
    ], ['src/' + f for f in LIBCXXABI_SRC])

    U = os.path.join(llvm, 'libunwind')
    u_out = os.path.join(SRC, 'libunwind')
    copytree(os.path.join(U, 'include'), os.path.join(u_out, 'include'))
    for f in os.listdir(os.path.join(U, 'src')):
        if f.endswith(('.h', '.hpp')) or f in LIBUNWIND_SRC:
            copy(os.path.join(U, 'src', f), os.path.join(u_out, 'src', f))
    copy(os.path.join(U, 'LICENSE.TXT'), os.path.join(u_out, 'LICENSE.TXT'))
    write_list('libunwind.txt', [
        'libunwind for %s: what walks the stack when a C++ exception is thrown.' % ARCH,
        "The EHABI, SEH, sjlj, wasm and AIX sources are other platforms'. Relative",
        'to sources/libunwind.',
    ], ['src/' + f for f in LIBUNWIND_SRC])


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--work', default=os.path.join(HERE, '.work'),
                    help='where upstream sources are downloaded (reused if present)')
    args = ap.parse_args()
    musl, llvm = fetch(args.work)
    for d in (SRC, LISTS):
        if os.path.exists(d):
            shutil.rmtree(d)
    m = build_musl(musl)
    b = build_builtins(llvm)
    build_cxx(llvm)
    size = sum(os.path.getsize(os.path.join(r, f)) for r, _, fs in os.walk(OUT) for f in fs)
    print('arm64-linux: %d musl, %d builtins, %d libc++, %d libc++abi, %d libunwind files; %.1f MB'
          % (len([f for f in m if not f.startswith('crt/')]), len(b), len(LIBCXX_SRC),
             len(LIBCXXABI_SRC), len(LIBUNWIND_SRC), size / 1e6))


if __name__ == '__main__':
    main()
